// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A permit risk assessment AI agent.
 *
 * - assessPermitRisk - A function that handles the permit risk assessment process.
 * - AssessPermitRiskInput - The input type for the assessPermitRisk function.
 * - AssessPermitRiskOutput - The return type for the assessPermitRisk function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AssessPermitRiskInputSchema = z.object({
  description: z.string().describe('The description of the permit.'),
  ppeChecklist: z.string().describe('The PPE checklist for the permit.'),
});
export type AssessPermitRiskInput = z.infer<typeof AssessPermitRiskInputSchema>;

const AssessPermitRiskOutputSchema = z.object({
  riskLevel: z
    .string()
    .transform((val) => val.toLowerCase())
    .pipe(z.enum(['low', 'medium', 'high']))
    .describe('The risk level of the permit.'),
  justification: z
    .string()
    .describe('The justification for the risk level assessment.'),
});
export type AssessPermitRiskOutput = z.infer<typeof AssessPermitRiskOutputSchema>;

export async function assessPermitRisk(input: AssessPermitRiskInput): Promise<AssessPermitRiskOutput> {
  return assessPermitRiskFlow(input);
}

const prompt = ai.definePrompt({
  name: 'assessPermitRiskPrompt',
  input: {schema: AssessPermitRiskInputSchema},
  output: {schema: AssessPermitRiskOutputSchema},
  prompt: `You are a safety officer assessing the risk level of a permit.

  Based on the permit description and PPE checklist, you will determine the risk level (low, medium, or high) and provide a justification for your assessment.

  You MUST respond with a valid JSON object that conforms to the following schema:
  {
    "riskLevel": "low" | "medium" | "high",
    "justification": "A brief explanation for the assessed risk level."
  }

  Permit Details:
  Description: {{{description}}}
  PPE Checklist: {{{ppeChecklist}}}`,
});

const assessPermitRiskFlow = ai.defineFlow(
  {
    name: 'assessPermitRiskFlow',
    inputSchema: AssessPermitRiskInputSchema,
    outputSchema: AssessPermitRiskOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error('The AI failed to generate a valid risk assessment.');
    }
    return output;
  }
);
