spring:
  application:
    name: hindalco-cpsms-backend
  
  # Database Configuration - PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/cpsms_db
    username: ${DB_USERNAME:cpsms_user}
    password: ${DB_PASSWORD:cpsms_password}
    driver-class-name: org.postgresql.Driver
    
    # Connection Pool Settings
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop  # Changed to create-drop for initial testing
    show-sql: true  # Enable SQL logging for debugging
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true

  # Flyway Migration (disabled for initial testing)
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

server:
  port: 8081
  servlet:
    context-path: /api

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000